spring.application.name=hotelmanagement

server.port=8085

# use Atlas:
spring.data.mongodb.uri=mongodb+srv://hotelUser:Hotel12345%40@hotelcluster.dlq7hoa.mongodb.net/hotelmanagement?retryWrites=true&w=majority&appName=hotelcluster
spring.data.mongodb.database=hotelDB

# JWT Configuration
jwt.secret=RoyalOpulenceSuperStrongSecretKeyForJWT_2025_XYZ
jwt.expiration=86400000

