
# -------------------------------------------------
# 🔧 SERVER CONFIGURATION
# -------------------------------------------------
spring.application.name=royal-opulence-backend
<<<<<<< HEAD
server.port=8081
=======
server.port=9001
>>>>>>> ae1e56b3ddb624b1593dca097864cefa37c50ab3


# -------------------------------------------------
# 🍃 MONGODB (LOGS, MEDIA, NOTIFICATIONS)
# -------------------------------------------------
spring.data.mongodb.uri=mongodb+srv://Buddhika:Kn20010925@hotelroomcluster.e01om9u.mongodb.net/?appName=HotelRoomCluster
spring.data.mongodb.database=royal_opulence_mongo

# -------------------------------------------------
# 🔐 JWT CONFIGURATION
# -------------------------------------------------
jwt.secret=U2VjdXJlU3ByaW5nQm9vdEtleUdvZXNIU0gyNTYyMDI1Q29uZmlybWVk
jwt.expiration=36000000000


# -------------------------------------------------
# 📧 MAIL CONFIGURATION (Optional)
# -------------------------------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@gmail.com
spring.mail.password=your_email_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# -------------------------------------------------
# 🌐 CORS CONFIG (Optional)
# -------------------------------------------------
spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*

#-------------------------------------------------
# Stripe (Test mode only)
#-------------------------------------------------
stripe.secretKey=sk_test_51SegGzL6FIjjiPhXreIsl3JRGxCa013KTJZMPA8lug3xXANDgArXcFOCAhiyWJZvMd8cmj3FoWzD7dmVnWz7jxXe001C7Nzdnx
stripe.webhookSecret=whsec_xxxxxxxxxxxxxxxxx
VITE_STRIPE_PUBLISHABLE_KEY=pk_test_51SegGzL6FIjjiPhXhtWv7V86kQHUxoPjuzFCMpWJt7cmC5nZAhxJ2uhBRSXpwlVHkkXw5EYRJaMtd2Vl57jLw1YF00jTfpHXpc

